### ISSUE TITLE
Renamed preprocessor directives: USE_JB, JB_TEMPERATURE_FRACTION

### ISSUE THREAD

**Issue by sjbradshaw** [rice-solar-physics/hydrad_tools#48]
The USE_MIKIC and MIKIC_TEMPERATURE_FRACTION preprocessor directives have been changed to USE_JB and JB_TEMPERATURE_FRACTION. This is because HYDRAD uses the updated method of modifying the thermal conduction developed by Johnston & Bradshaw.

**Comment by wtbarnes** [comment]
Great thanks! I'll get around to adding these soon. @cdj3 this will likely be of interest to you as well.
