### ISSUE TITLE
Environment variables for OpenMP and 6-level hydrogen atom

### ISSUE THREAD

**Issue by sjbradshaw** [rice-solar-physics/hydrad_tools#54]
Using the OpenMP version of HYDRAD requires the pre-processor directive #define OPENMP to be added in the HYDRAD/source/config.h file.

Using the 6-level hydrogen atom requires both #define OPTICALLY_THICK_RADIATION and #define NLTE_CHROMOSPHERE to be added in the Radiation_Model/source/config.h file.

There is also a new directive which replaces #define USE_MIKIC with #define USE_JB. Here, JB refers to the new Johnston-Bradshaw method of broadening the transition region to speed up calculations that involve a strong heat flux from the corona. A Letter describing this method is currently being written-up.

**Comment by wtbarnes** [comment]
Thanks @sjbradshaw. To summarize:

* `HYDRAD/source/config.h`
  * `OPENMP` (bool)
* `Radiation_Model/source/config.h`
  * `NLTE_CHROMOSPHERE` (bool)
  * `OPTICALLY_THICK_RADIATION` (bool)

Looking at file templates, it looks like the last two are already implemented. Are there any additional configuration files that need to be generated for the 6-level H atom?

**Comment by wtbarnes** [comment]
If `OPENMP` is true, the code should also use the OpenMP build script to compile the code rather than the default one.

**Comment by wtbarnes** [comment]
The jump condition fix is covered in #48

**Comment by sjbradshaw** [comment]
There shouldn’t be any other config files. Just run the initial conditions first to generate the chromosphere with the 6-level H atom and then run HYDRAD.

**Comment by wtbarnes** [comment]
Closed by #61
